//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrapherAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Графики
    {
        public int id { get; set; }
        public Nullable<int> метод_id { get; set; }
        public byte[] изображение { get; set; }
        public string описание { get; set; }
    
        public virtual Методы Методы { get; set; }
    }
}
