//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrapherAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ответы_на_тесты
    {
        public int id { get; set; }
        public Nullable<int> тест_id { get; set; }
        public string вариант_ответа { get; set; }
        public Nullable<bool> верный { get; set; }
    
        public virtual Тесты Тесты { get; set; }
    }
}
