//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrapherAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Тесты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Тесты()
        {
            this.Ответы_на_тесты = new HashSet<Ответы_на_тесты>();
        }
    
        public int id { get; set; }
        public string вопрос { get; set; }
        public Nullable<int> метод_id { get; set; }
        public string правильный_ответ { get; set; }
    
        public virtual Методы Методы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ответы_на_тесты> Ответы_на_тесты { get; set; }
    }
}
